version: '3'

services:
  app:
    container_name: 'dfs_app'
    restart: always
    build: ./app
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - app-data:/static
    env_file: 
      - .env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  nginx:
    container_name: 'dfs_ngnix'
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - .:/www/static
      - app-data:/usr/src/app/static
    links:
      - app:app
  postgres:
    image: postgres:12-alpine
    container_name: 'dfs_postgress'
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  app-data:
  postgres-data:
