version: '3'

services:
  app:
    build: ./app
    container_name: 'frs_dev_app'
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file: 
      - .env

  redis:
    image: redis:5-alpine
    container_name: 'frs_dev_redis'
    expose:
      - 6379

volumes:
  app:

